### ISSUE TITLE
Sawed off

### ISSUE THREAD

**Issue by darkdragon1076** [Documantation12/Femboy-krunker-cheat#2]
can you make the aimbot so that sawed off (secondary weapon) do not lock at someone. The weapon isn't made do shoot players with, the damage is low, it is made for shotgun jumping.

**Comment by Documantation12** [comment]
I recommend setting a fov 
![image](https://github.com/Documantation12/Femboy-krunker-cheat/assets/134162456/3f264cc2-84c9-427b-b942-3d1906d33f6a)
